env:
  global:
    - CC_TEST_REPORTER_ID=$CodeClimateToken
language: php
php:
  - '7.1'
cache:
  directories:
  - $HOME/.composer/cache/files
install:
  - sudo apt-get install ant
  - ant
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - phpunit
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
